// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTnxQxsmduhZZW-KsK-UwlGagSWT5a-80',
    appId: '1:483427277183:web:3e1561af749877e476224a',
    messagingSenderId: '483427277183',
    projectId: 'partbarcode-db',
    authDomain: 'partbarcode-db.firebaseapp.com',
    storageBucket: 'partbarcode-db.appspot.com',
    measurementId: 'G-6HE2VT4N57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOIPWWq6FpzAcOMVXckUWyqpxHqF0g2gU',
    appId: '1:483427277183:android:8906485595ea6ac376224a',
    messagingSenderId: '483427277183',
    projectId: 'partbarcode-db',
    storageBucket: 'partbarcode-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR6OxBEOEusDc5XIudQzcYb_uxnkDSIMs',
    appId: '1:483427277183:ios:3e5b25f55960079276224a',
    messagingSenderId: '483427277183',
    projectId: 'partbarcode-db',
    storageBucket: 'partbarcode-db.appspot.com',
    iosClientId: '483427277183-9hbed8c3b1dlu4scollq1gi5jclusj1u.apps.googleusercontent.com',
    iosBundleId: 'com.barcode.barcodeScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR6OxBEOEusDc5XIudQzcYb_uxnkDSIMs',
    appId: '1:483427277183:ios:cd1d69345124f44c76224a',
    messagingSenderId: '483427277183',
    projectId: 'partbarcode-db',
    storageBucket: 'partbarcode-db.appspot.com',
    iosClientId: '483427277183-95eh53giktfij9ekq3no1l8hrakpkug4.apps.googleusercontent.com',
    iosBundleId: 'com.barcode.barcodeScanner.RunnerTests',
  );
}
